inherit_mode:
  merge:
    - Exclude

require:
  - standard

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop/rails.yml
  - .rubocop/rspec.yml
  - .rubocop_todo.yml
  - .rubocop/strict.yml
  - .rubocop-overrides.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

  Exclude:
    - bin/*
    - config/puma.rb
    - db/**/*.rb
    - gemfiles/*
    - node_modules/*
    - vendor/*
    - tmp/*
